// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context_lifecycle.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listRecentAssistantMessagesBySession = `-- name: ListRecentAssistantMessagesBySession :many
SELECT
  id,
  role,
  metadata,
  created_at
FROM bot_history_messages
WHERE session_id = $1
  AND role = 'assistant'
  AND metadata IS NOT NULL
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListRecentAssistantMessagesBySessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	MaxCount  int32       `json:"max_count"`
}

type ListRecentAssistantMessagesBySessionRow struct {
	ID        pgtype.UUID        `json:"id"`
	Role      string             `json:"role"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRecentAssistantMessagesBySession(ctx context.Context, arg ListRecentAssistantMessagesBySessionParams) ([]ListRecentAssistantMessagesBySessionRow, error) {
	rows, err := q.db.Query(ctx, listRecentAssistantMessagesBySession, arg.SessionID, arg.MaxCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentAssistantMessagesBySessionRow
	for rows.Next() {
		var i ListRecentAssistantMessagesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
